source :rubygems

gem 'rails', '7.0.3.1'
gem 'activesupport', '7.0.3.1'
gem 'activerecord', '7.0.3.1'

gem 'ruport', '1.6.3'
gem 'activemerchant', '1.126.0', :require => 'active_merchant'
gem 'erubis', '2.7.0'
gem 'awesome_nested_set', '1.4.3'
gem 'friendly_id', '~> 3.1'
gem 'acts_as_singleton', '0.0.5'
gem 'pg', '0.9.0'
gem 'pebbles', :path => '..'
gem 'aasm', '2.0.2'
gem 'will_paginate', '~> 2.3.11'
gem 'rails_xss', '0.1.3'
gem 'ssl_requirement', '0.1.0'
gem 'carrierwave', '0.4.10'
gem 'acts_as_reportable', '1.1.1'

group :test do
  gem 'rspec', '1.3.0'
  gem 'cucumber', '8.0.0'
  gem 'cucumber-rails', '0.3.2'
  gem 'factory_girl', '1.3.2'
  gem 'rspec-rails', '5.1.2'
  gem 'capybara', '0.3.9'
  gem 'database_cleaner', '0.5.2'
  gem 'launchy', '0.3.7'
  gem 'pickle', '~> 0.4'
end
