# Generated by the asset_copier plugin
# http://github.com/pelargir/asset_copier

require File.expand_path(File.dirname(__FILE__) + '/../lib/pebbles/asset_copier')

namespace :pebbles do
  desc "Install files required by pebbles"
  task :install do  
    Pebbles::AssetCopier.copy "pebbles"
  end
end