class ProductAccessory < ActiveRecord::Base

  belongs_to :product
  belongs_to :accessory, :class_name => 'Product'
  has_many :cart_items

  def name
    accessory.name
  end

  def price
    accessory.accessory_price(product)
  end

  # finds accessories from the crazy hash generated by the combined products/_product_accessories
  # and products/_accessory_options views. An accessories_hash for a selected_accessory id 82 with
  # an option selection of id 45 looks like this: {"82"=>{"options"=>"45", "82"=>"1"}}
  def self.selected_accessories(accessories_hash)
    selected_accessories = Array.new
    accessories_hash.keys.each do |k|
      if accessories_hash[k][k] == '1'
        accessory = Product.find(k.to_i)
        selected_accessories << accessory
      end
    end
    selected_accessories
  end
end